//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konsolika.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int kod_inventory { get; set; }
        public int kod_sewing_tools { get; set; }
        public int kod_materials { get; set; }
        public int kod_sewing_accessories { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Sewing_accessories Sewing_accessories { get; set; }
        public virtual Sewing_tools Sewing_tools { get; set; }
    }
}
