    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан по шаблону.
    //
    //     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
    //     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace Dereev_21._101.Models
    {
        using System;
        using System.Collections.Generic;
    
        public partial class Workers
        {
            public int id_worker { get; set; }
            public string Surname { get; set; }
            public string Name { get; set; }
            public string Otchestvo { get; set; }
            public Nullable<int> id_user { get; set; }
    
            public virtual User User { get; set; }
        }
    }
